language: perl
sudo: false
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

install:
  - cpanm --quiet --notest --skip-satisfied Dist::Zilla
  - cpanm --notest --metacpan --skip-satisfied Test::Pod
  - dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
  - dzil listdeps --author | cpanm --quiet --notest --skip-satisfied
  - dzil listdeps | grep -vP '[^\w:]' | cpanm --quiet --notest --skip-satisfied

script:
   - dzil smoke --release --author
