language: perl
sudo: false
perl:
   - "5.20"
   - "5.18"
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"
   - "5.8"

install:
   # for testing
   - cpanm --notest --metacpan --skip-satisfied Test::Pod 
   - cpanm --notest --metacpan --skip-satisfied --installdeps .
   - echo y | perl Makefile.PL
   - make manifest
   - export AUTHOR_TESTING=1

script:

   - make disttest
   - make install

