language: perl
sudo: false
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto

install:
  - cpanm --notest --metacpan --skip-satisfied Test::Pod
  - cpan-install --deps
  - cpan-install --coverage
